### ISSUE TITLE
Error: OAuth2Strategy requires a clientID option

### ISSUE THREAD

**Issue by natevw** [tessel/oauth#30]
Getting this after following (I think) all the instructions in the README, as soon as I load http://127.0.0.1:3002/register.

```
$ PORT=3002 npm start

> tessel-oauth@0.0.1 start /Users/natevw/Desktop/Clients/Technical_Machine/oauth
> node ./bin/www


/Users/natevw/Desktop/Clients/Technical_Machine/oauth/node_modules/passport-google-oauth/node_modules/passport-oauth/lib/passport-oauth/strategies/oauth2.js:66
  if (!options.clientID) throw new Error('OAuth2Strategy requires a clientID o
                               ^
Error: OAuth2Strategy requires a clientID option
    at Strategy.OAuth2Strategy (/Users/natevw/Desktop/Clients/Technical_Machine/oauth/node_modules/passport-google-oauth/node_modules/passport-oauth/lib/passport-oauth/strategies/oauth2.js:66:32)
    at new Strategy (/Users/natevw/Desktop/Clients/Technical_Machine/oauth/node_modules/passport-google-oauth/lib/passport-google-oauth/oauth2.js:48:18)
    at Object.<anonymous> (/Users/natevw/Desktop/Clients/Technical_Machine/oauth/controllers/application_controller.js:60:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/natevw/Desktop/Clients/Technical_Machine/oauth/routes.js:3:11)
```

**Comment by natevw** [comment]
The workaround commit has been merged into master, so I think this no longer applies.
